server:
  port: 2080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2080/eureka/
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetchRegistry: false
  server:
    #关闭自我保护机制，以此保证在本地测试时能正确剔除不正常运行的微服务，生产环境可以设置为true，若删除这一条，因为默认值为true
    enable-self-preservation: false