server:
  port: 2080
eureka:
  client:
    service-url:
      defaultZone: http://liwei:wwwliwei001com@localhost:2080/eureka/
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetchRegistry: false
  server:
    #关闭自我保护机制，以此保证在本地测试时能正确剔除不正常运行的微服务，生产环境可以设置为true，若删除这一条，因为默认值为true
    enable-self-preservation: false
